### ISSUE TITLE
Cannot find the H-MOG dataset

### ISSUE THREAD

**Issue by nisheshawale** [dynobo/ContinAuth#1]
I am not able to access the H-MOG dataset from the link as well as in the folder named 'data'.
Please help !!!

**Comment by dynobo** [comment]
Thanks for the hint! Indeed, the original link seems to be down. Unfortunately the datset's
 licence doesn't allow to share or mirror it.

The information page (without the dataset itself!) can still be viewed on the [Internet Archive](https://web.archive.org/web/20181005073637/http://www.cs.wm.edu/~qyang/hmog.html). Maybe you could try to contact the authors?

I'll keep this ticket open for some time, maybe the dataset get's republished or someone finds a legitimate mirror... Please report back any relevant information! Thanks!

**Comment by engividal** [comment]
@nisheshawale the link of the dataset is alive again: http://www.cs.wm.edu/~qyang/hmog.html

**Comment by dynobo** [comment]
Thanks a lot, @engividal, for your comment! Good to know, that the dataset is available again! :-)
